name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-image:1.0.0

    - uses: pmorelli92/github-container-registry-build-push@2.0.0
      name: Build and Publish latest service image
      with:
        github-push-secret: ${{secrets.TEST_GITHUB_TOKEN}}
        docker-image-name: test-image
        docker-image-tag: $(date +%s) # optional
        dockerfile-path: ./Dockerfile # optional
        #build-context: ./src/svc # optional
        build-only: false # optional
